### ISSUE TITLE
Cannot Find Path ?

### ISSUE THREAD

**Issue by pctan9** [sebastienvercammen/ptc-acc-gen#107]
![image](https://cloud.githubusercontent.com/assets/23416683/22627308/e30596b0-ec14-11e6-9e19-7dfa69fa1b4a.png)

I have this issue running the Program on Window 7 Premium, 64 Bits. Even after manually typing in "PATH"

![image](https://cloud.githubusercontent.com/assets/23416683/22627322/27c6aa96-ec15-11e6-90d6-025073c518cb.png)

Not sure what else I can do to run this

**Comment by jagauthier** [comment]
You need to run the "git bash" program.

**Comment by drallieiv** [comment]
it's not ptc-acc-gen that you need in your path, but git itself.
You could use git bash or use one of the GUI listed here : 

https://git-scm.com/downloads/guis

**Comment by pctan9** [comment]
Thanks for that, and now there is something else ?

![image](https://cloud.githubusercontent.com/assets/23416683/22638222/d8514a80-ec9a-11e6-8a5d-c4955abba953.png)

**Comment by pctan9** [comment]
![image](https://cloud.githubusercontent.com/assets/23416683/22638921/7be8cbc4-ec9f-11e6-9a23-c3ab0268032d.png)
 When I tried to create Acc, this is the new error

**Comment by jagauthier** [comment]
basically, stop double clicking things, and open git bash and do everything from the command line.

**Comment by sebastienvercammen** [comment]
PEBKAC.
