### ISSUE TITLE
Enabled full debug mode

### ISSUE THREAD

**Issue by JRCrawford** [sebastienvercammen/ptc-acc-gen#108]
I've installed this on a Linux server with the following config file: http://i.imgur.com/iRmaQvY.png however even with debugging enabled all I get as an output is this: http://i.imgur.com/iVXEBZZ.png

It isn't generating anything and the lack of debugging info makes it a bit tricky to see why.

**Comment by jasondinh** [comment]
Doesn't work in with headless Linux

**Comment by JRCrawford** [comment]
It looks like this can be done via exporting debug.  Closing this ticket
