### ISSUE TITLE
Error: "Cannot read property 'textContent' of null"

### ISSUE THREAD

**Issue by vlacorte** [sebastienvercammen/ptc-acc-gen#110]
Filled the captcha just fine (manually), but got a loop of errors as in the title and `Unable to evaluate PTC signup page... Trying again.`

Did "Nintendo" change the signup form structure again?

Edit: prior to those errors I got a `Unable to evaluate PTC DOB signup page... Trying again.`

**Comment by Arengo** [comment]
Use GitHub project novskey/PalletTown temporarily until ptc-acc-gen has been updated.

**Comment by vlacorte** [comment]
@Arengo thank you for the advice, will do that!

**Comment by Arengo** [comment]
You might want to have a look into the RocketMap Discord server in general.

**Comment by jagauthier** [comment]
I tested this with pikaptcha and it worked fine. I don't think the sign up form changed.
