### ISSUE TITLE
setting trainer name

### ISSUE THREAD

**Issue by bellowsj** [sebastienvercammen/ptc-acc-gen#79]
When I run `node pogo.js` I get the following error:
`Failed to complete the tutorial... ERROR: { [StopError: Status code 3 received from RPC]
  name: 'StopError',
  message: 'Status code 3 received from RPC' }`

I believe my pogobuf is running the latest version:
`$ npm list pogobuf
  nintendo-ptc-account-generator@2.7.0 C:\Users\Jason\Code\IVs\ptc-acc-gen
`-- pogobuf@1.7.0`

When I login to the account, it looks like they have caught the starter pokemon but the trainer name is not yet set.

**Comment by FrostTheFox** [comment]
I suppose this is a bug in pogoplayer (aka NOT MY PROBLEM ;) ), but in reality trainer name is unneeded. I'll look into it but no promises here, especially since I can't push to the pogoplayer repo.

**Comment by bellowsj** [comment]
Trainer name is required if your scanner is doing -gi. Without trainer name set it seems that trying to scan and pull gym info will give errors.

**Comment by eXtaPlY** [comment]
Usage guide:

Make sure you've latest node.js and npm!
Download .zip or clone
Run this inside directory: npm install
Rename accounts.csv.example to accounts.csv
Input data in accounts.csv in one of these formats:
auth,username,password,lat,lng,trainerName (will try to assign trainer name)
auth,username,password,lat,lng (wont try to assign trainer name)
run node pogo.js
Todo:

??? - send an issue with suggestion!

**Comment by eXtaPlY** [comment]
The original Text from PogoPlayer, i think when you run with the changes, it will runs ;-)

**Comment by Aleeeeeeeex** [comment]
When you get that error the trainer-name is already set! ptc-acc-gen runs pogo.js after creating users.

**Comment by sebastienvercammen** [comment]
PogoPlayer issue, closing.
