### ISSUE TITLE
[Request] output format without lat/lon/name

### ISSUE THREAD

**Issue by dikkedeur** [sebastienvercammen/ptc-acc-gen#89]
I have a request, or somebody knows how to change it easily in the code.
right now the output format of the made accounts is

PTC,ACCOUNTNAME,PASSWORD,LAT,LON,ACCOUNTNAME

can it be made like 

PTC,ACCOUNTNAME,PASSWORD
??
that way we can use the output right away in the pogom map.

**Comment by BrownSlaughter** [comment]
pretty sure if you just edit line 54 of index.js
`var outputFormat = "ptc,%NICK%,%PASS%,%LAT%,%LON%,%UN%\r\n"; // Format used to save the account data in outputFile. Supports %NICK%, %PASS%.
`
and remove unwanted output it should do what you want

**Comment by dikkedeur** [comment]
thanks, it kinda works, i do get an error though, the account is kinda active and i can login but i still need to accept the tos, maybe thats whats the error is about.

ptc-acc-gen v2.8.0 by Sébastien Vercammen and Frost The Fox (and Github contribs)
Creating account 0 of 1
Start recaptcha solving
Creating account 1 of 1
Start recaptcha solving
, Location: undefined,undefinedlszr0, Password: djfhkshjkgdf
, Location: undefined,undefinedlszr1, Password: jdhfkghjkdfg
Failed to initialize client for hfgdj... ERROR: [Error: Invalid response received from PTC login]
Failed to initialize client for uriewo... ERROR: [Error: Invalid response received from PTC login]
Find the generated accounts in PogoPlayer/accounts.csv

**Comment by BrownSlaughter** [comment]
ah yeah I failed to think about the TOS part of the script.

**Comment by FrostTheFox** [comment]
This is required for the ToS portion of the script.

**Comment by FrostTheFox** [comment]
I suppose I can leave this open, I'll see what @sebastienvercammen thinks, but personally i'd leave it.

**Comment by sebastienvercammen** [comment]
You can change the `outputFormat` and lat/lon are required for account validation with PogoPlayer. This is a non-issue.
