### ISSUE TITLE
Servers are acting up

### ISSUE THREAD

**Issue by unholygod91** [sebastienvercammen/ptc-acc-gen#93]
Everything was working fine the last time i made accounts, but now i cant make a single one using gmail or hotmail. i've tried different names and emails as well as without 2captcha and with 2captcha. Not sure what changed or how to fix it. any insight to the cause would be greatly appreciated. i tried discord help channel but everyone was on a different topic and i was ignored.

**Comment by OctHex2016** [comment]
I facing this problem too

**Comment by ivar111** [comment]
Pikaptcha is also acting up, from issues reported there, it seems either that the password field has changed and requires symbols now, or that the Gmail trick is fixed?

**Comment by unholygod91** [comment]
its both. i proposed a way around this

**Comment by sebastienvercammen** [comment]
"Servers are acting up" refers to a single thing: the Nintendo servers were acting up and returning an invalid response. Only patience (and Nintendo) can fix this.

The other issue was that Nintendo updated their password requirements. I've updated the code to reflect these changes.

The + e-mail trick has also been patched for Gmail (it now has a cooldown), so we now recommend using a different e-mail provider (e.g. hotmail). You can still forward account creation e-mails to Gmail afterwards and use our auto-verifier on Gmail. These edits are also in the updated readme.
