### ISSUE TITLE
Gmail trick dont work 100%

### ISSUE THREAD

**Issue by tokar86a** [sebastienvercammen/ptc-acc-gen#94]
I seems to have trouble whit this Gmail trick. first account can be crated whit out any problem but after that it ask me about e-mail verification again.

**Comment by sebastienvercammen** [comment]
This is correct, it seems Nintendo has patched the + e-mail trick (for Gmail). Some users on our Discord have tested and reported that Gmail now requires a 200+ second cooldown period between creation of accounts. Using another e-mail provider (tested with hotmail) still works.

I've added this information to the top of the readme in the latest commit.
