### ISSUE TITLE
problem with email when creating account

### ISSUE THREAD

**Issue by lamolivierhk** [sebastienvercammen/ptc-acc-gen#98]
it seems like niantic no longer accept email address with the + sign when filling up the form.  Is there a workaround ?

the dot still work but that would be limited to the char length of your email address...

**Comment by walaoaaa1234** [comment]
[It seems Nintendo has patched the + e-mail trick for Gmail. Some users on our Discord have tested and reported that Gmail now requires a 220+ second cooldown period between creation of accounts. Using another e-mail provider (tested with hotmail) still works. For automatic validation, forward all PTC account e-mails to a Gmail account and use our auto-verifier.](https://github.com/sebastienvercammen/ptc-acc-gen/blob/master/README.md)
#94 #96

**Comment by GouSao** [comment]
@walaoaaa1234 hotmail+ trick is not working anymore too.

**Comment by Johnforeland** [comment]
@GouSao hotmail+ seems to work for me

**Comment by radzuky** [comment]
Regardless of email service, I think there is a time out on the IP on how fast you can make accounts. Usually I have to wait 5 minutes between accounts using Hotmail, or else I don't receive the email confirmation.

**Comment by sebastienvercammen** [comment]
This was a case of RTFM 16 days ago and it partly still is. It works for most but not for some - either way, fixing the code that other people put in while I was gone would take up so much time that I decided to rewrite the entire thing.

Focus is currently on maintaining PokémonGo-Map, but when I find time there'll be a better gen. In the meantime, it's not beneficial for me to keep chasing e-mail requirement changes.
